version: '3.8'

services:
  app:
    build:
      args:
        user: www-data
        uid: 33
      context: ./
      dockerfile: Dockerfile
    image: cv
    container_name: cv-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - cv

  db:
    image: mysql:8.0
    container_name: cv-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cv
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: kevin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - cv

  adminer:
    image: adminer
    container_name: cv-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - db:db
    networks:
      - cv

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email molinakevinalejandro@gmail.com --agree-tos --no-eff-email -d molinakev.in -d www.molinakev.in -d es.molinakev.in -d en.molinakev.in -d de.molinakev.in
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/logs:/var/log/letsencrypt
      - ./docker/certbot/data:/usr/share/nginx/html/letsencrypt

  nginx:
    image: mbarthelemy/nginx-geoip
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/dhparam:/etc/nginx/dhparam
      - ./docker/certbot/conf:/etc/nginx/ssl
      - ./docker/certbot/data:/usr/share/nginx/html/letsencrypt
    networks:
      - cv

  mailserver:
    image: dirtsimple/poste.io
    restart: unless-stopped
    ports:
      - "25:25"
      - "81:80"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/mail-data/:/data
    environment:
      - HTTPS=ON
    hostname: mail.molinakev.in
    network_mode: "host"

networks:
  cv:
    driver: bridge
